version: '3.8'

services:
  backend:
    build:
      context: ./backend-node
      dockerfile: Dockerfile
    container_name: vendor-backend
    ports:
      - "3000:3000"
    volumes:
      - vendor-data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vendor-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - VITE_API_URL_NODE=http://localhost:3000/api

volumes:
  vendor-data:
    driver: local 